spring:
  application:
    name: logrus-api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8080

logrus:
  api:
    service-name: logrus-api
